#[Info]
site_name: Xpm's Robot Lab
site_url: https://xpmrobot.cn
cname: xpmrobot.cn
site_author: xpm00

#[UI]
theme:
  name: material
  custom_dir: overrides
  # custom_dir: material/.overrides
  # font:
  #   text: Bitter
  #   code: Roboto Mono
  logo: images/portrait.jpg
    # material/library
    # admonition:
    #   <type>: material/file-alert-outline

  favicon: images/favicon.ico
  palette:

    
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: deep purple # 上方的
      accent: indigo # 链接等可交互元件的高亮色
      # teal 
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black 
      accent: indigo
      # teal
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features: 
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    # - navigation.instant 
    #- header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate 
  language: zh # 一些提示性的文字会变成中文
  

  icon: 
    repo: fontawesome/brands/github #右上角图标
edit_uri: edit/main/docs # 编辑按钮跳转的链接 
repo_url: https://github.com/xiepm/xiepm.github.io # 右上角点击跳转的链接
repo_name: xiepm.github.io # 右上角的名字

# [Navigtion]
nav:
  - Home: index.md
  - 控制理论:
    - 学习大纲: Control-Theory/learning-plan.md
    - 控制理论笔记: Control-Theory/notes.md
  - 机器人学:  
    - 学习大纲: Robotics/learning-plan.md
  - ROS:
    - ROS2:
      - 学习大纲: Robot Operating System/ROS2/learning-plan.md
    - micro-ros: 
      - 学习大纲: Robot Operating System/micro-ros/learning-plan.md
  - LINUX: 
    - 学习大纲: LINUX/learning-plan.md
  - 嵌入式:  
    - 学习大纲: Embedded development/learning-plan.md

  - 开源项目:  
    - 学习大纲: Open-source/learning-plan.md
    - 项目推荐: Open-source/project-recommendation
  - 数学:  
    - 学习大纲: MATH/learning-plan.md
  - 编程:  
    - 学习大纲: Programming/learning-plan.md
  - AI:  
    - 学习大纲: AI/learning-plan.md
  - 差生文具多:  
    - 学习大纲: TOOLS/learning-plan.md
    - 杂七杂八的奇淫技巧: 
      - 系统架构设计: TOOLS/hotchpotch/system-design
  - 论文:  
    - 学习大纲: PAPER/learning-plan.md
  - 网络:  
    - 学习d大纲: Network/learning-plan.md
  - OS:  
    - 学习大纲: Operating-System/learning-plan.md
  - 友链: about/link.md
    # - 如何给MKdocs添加友链: blog/Mkdocs/linktech.md

  - 留言板: waline.md
  - 关于:
    - 个人简介: about/geren.md
    # - 个人简历: about/个人简历2.pdf
    - My Goal: about/goal.md
    - Github主页介绍: about/xiepm.md
    - 网站制作: about/web.md
    - 支持作者: about/zcw.md
    #- 友链: about/link.md
    - 毕业之前值得去做的30件事: about/biye.md
    - 免责声明: about/shengming.md
    - Test: about/test.md
    - 404公益页面: about/404.md
    - For lover: about/Foryou.md
    - 亿点古话: about/oldsaying.md
  - Blogger:
    - index: blog/index.md

    

  
copyright: Copyright &copy; 2022~2023 xiepm/All Rights Reserved. # 左下角的版权声明
  

extra:
  generator: true  #删除页脚显示“使用 MkDocs 材料制造”
  social:
    # - icon: fontawesome/brands/x-twitter 
    #   link: https://twitter.com/
    - icon: fontawesome/brands/github
      link: https://github.com/xiepm
    
    - icon: fontawesome/regular/envelope
      link: mailto:<xpm0_0@163.com> #联系方式
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/453156065?spm_id_from=333.1007.0.0
  # analytics: 
  #   provider: google
  #   property: G-29HZMNR0KG
  #   feedback:
  #     title: 此页面有帮助吗？
  #     ratings:
  #       - icon: material/thumb-up-outline
  #         name: This page was helpful
  #         data: 1
  #         note: >-
  #           谢谢你的反馈！
  #       - icon: material/thumb-down-outline
  #         name: This page could be improved
  #         data: 0
  #         note: >- 
  #           Thanks for your feedback! Help us improve this page by
  #           using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
  
  # consent:
  #   title: Cookie consent
  #   description: >- 
  #     我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。
  #     如果你同意,你可以帮助我们让我们的网站更好

    

plugins:
  # - glightbox
  - search
  - blog:
      post_date_format: full #时间
      draft: true
      draft_if_future_date: true #自动将具有未来日期的帖子标记为草稿
      post_readtime: true
      post_readtime_words_per_minute: 265  #计算帖子的阅读时间时读者每分钟预计阅读的字数
      post_url_format: "{date}/{slug}"
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      # categories_toc: true
      # pagination_per_page: 5
      pagination_url_format: "page/{page}"
      authors_file: "{blog}/.authors.yml"  #作者信息
  - tags:
      tags_file: tag.md  #分类标签

  

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  # - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      # emoji_index: !!python/name:material.extensions.emoji.twemoji
      # emoji_generator: !!python/name:material.extensions.emoji.twemoji

  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: "\ue157"
  
extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - javascripts/mathjax-config.js
  # - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML


  - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js
  # - ckplayer/js/ckplayer.js
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/js/social-share.min.js
  - javascripts/backbound1.js
  # - javascripts/rellax.min.js
  - https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/add-html-label-6e56ed67.min.js
  # - https://res.zvo.cn/translate/translate.js  # Translate

extra_css:
  - stylesheets/extra.css
  # - stylesheets/extra1.css
  # - stylesheets/video.css
  - https://unpkg.com/@waline/client@v2/dist/waline.css
  - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.css
  - ckplayer/css/ckplayer.css
  - https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/css/share.min.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css  #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css

# crisp
# https://crisp.chat/en/
# crisp:
#   enable: true
#   website_id: 89ded6c2-1a10-47e3-af5d-f12e6a378547

# tidio:
#   enable: true
#   public_key: w3nvk9wmckvjf2iity4bwxicoj4yss9l
