site_name: Xpm_Robot
site_url: https://xiepm.github.io/mkdocs-site/docs
site_author: xpm
theme:
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
  #  - scheme: slate
  #    toggle:
  #      icon: material/brightness-4
  #      name: Switch to light mode